name: Light prices

on:
  workflow_dispatch:


jobs:
  Test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12.1"
      - name: Install Chrome
        run: sudo apt-get install google-chrome-stable
      - name: install dependencies
        run: pip install -r requirements.txt
      - name: run_test
        run: |
          pytest -v > test_result.txt 
          ls -l
        continue-on-error: true

  publish-result:
    runs-on: ubuntu-latest
    needs: Test
    name: Result publication
    steps:
      - name: result
        run: |
          message=$(cat test_result.txt)
          curl --location 'https://discord.com/api/webhooks/${{ secrets.WH_DISCORD }}' --header 'Content-Type: application/json' --data "{\"content\": \"$message\"}"
          curl --location 'https://api.telegram.org/bot6984990599:${{ secrets.TG_TOKEN }}/sendMessage' --header 'Content-Type: application/json' --data "{\"chat_id\": 270756677, \"text\": \"$message\"}"
